on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run tsc -- --noEmit && ./node_modules/.bin/jest

